import { getDeviceId } from './deviceId';
import { API_BASE } from './apiBase';

import i18n from '../i18n';

// Server error -> a message in the reader's language.
//
// The API answers with an English sentence in `error` (useful in logs and to
// anyone calling it directly) plus a `reason` code. Only the code is meant for
// people: the login screen showed the English sentence verbatim to all 17
// languages, which is the worst possible place for it - someone who cannot read
// why their sign-in failed simply stops trying.
const REASON_KEYS = {
  passwordTooShort: 'authError.passwordTooShort',
  subscribersOnly: 'authError.subscribersOnly',
  noSubscription: 'authError.noSubscription',
  linkFailed: 'authError.linkFailed',
  missingCredentials: 'authError.missingCredentials',
  badCredentials: 'authError.badCredentials',
  googleFailed: 'authError.googleFailed',
  accountExists: 'authError.accountExists',
  signupFailed: 'authError.signupFailed',
  badCode: 'authError.badCode',
  badEmail: 'authError.badEmail',
  codeSendFailed: 'authError.codeSendFailed',
};

function serverError(data, fallbackKey) {
  const key = data?.reason && REASON_KEYS[data.reason];
  return new Error(i18n.t(key || fallbackKey));
}


export async function requestRestoreCode(email) {
  const response = await fetch(`${API_BASE}/api/restore/request-code`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email }),
  });

  const data = await response.json();
  if (!response.ok) {
    throw serverError(data, 'restore.genericError');
  }
}

export async function verifyRestoreCode(email, code) {
  const deviceId = await getDeviceId();

  const response = await fetch(`${API_BASE}/api/restore/verify-code`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, code, deviceId }),
  });

  const data = await response.json();
  if (!response.ok) {
    throw serverError(data, 'restore.genericError');
  }

  return data.status;
}

// Password accounts are opt-in, subscriber-only (see api/auth.js) - this only
// ever runs from a device that's already entitled, to let that subscriber
// sign in with a password on OTHER devices later instead of requesting a
// fresh email code every time. Signup and signin share one endpoint
// (api/auth.js, dispatched via `action`) to stay within Vercel's Hobby-plan
// serverless function count limit.
export async function createPassword(password) {
  const deviceId = await getDeviceId();

  const response = await fetch(`${API_BASE}/api/auth`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'signup', password, deviceId }),
  });

  const data = await response.json();
  if (!response.ok) {
    throw serverError(data, 'restore.genericError');
  }

  return data.email;
}

export async function signInWithPassword(email, password) {
  const deviceId = await getDeviceId();

  const response = await fetch(`${API_BASE}/api/auth`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'signin', email, password, deviceId }),
  });

  const data = await response.json();
  if (!response.ok) {
    throw serverError(data, 'authError.badCredentials');
  }

  return data.status;
}

// PKCE (RFC 7636): a random verifier is kept only on this device, and its
// SHA-256 hash (the "challenge") is what actually travels in the URL to
// Google/Supabase. Only a one-time `code` comes back in the redirect - never
// a usable token - so nothing sensitive ever sits in browser history or
// server logs. This app has no client-side Supabase SDK (see project memory
// on why, bundle size), so the verifier/challenge pair is generated by hand
// with the Web Crypto API rather than the SDK's built-in PKCE support - this
// only runs on web (the Google button is gated to Platform.OS === 'web'),
// so window.crypto/sessionStorage are always available here.
const GOOGLE_PKCE_STORAGE_KEY = 'naturelens_google_pkce_verifier';

function base64UrlEncode(bytes) {
  let binary = '';
  bytes.forEach((byte) => { binary += String.fromCharCode(byte); });
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function generateCodeVerifier() {
  const bytes = new Uint8Array(32);
  window.crypto.getRandomValues(bytes);
  return base64UrlEncode(bytes);
}

async function generateCodeChallenge(verifier) {
  const data = new TextEncoder().encode(verifier);
  const digest = await window.crypto.subtle.digest('SHA-256', data);
  return base64UrlEncode(new Uint8Array(digest));
}

// Plain browser redirect to Supabase's own OAuth authorize endpoint - no
// client-side Supabase SDK needed (confirmed live via Supabase's docs: this
// endpoint works as a bare link, no apikey query param required). The
// code_verifier is stashed in sessionStorage so it survives the round trip
// to Google and back, then consumed once by completeGoogleSignIn below.
export async function getGoogleSignInUrl() {
  const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL;
  const origin = window.location.origin;
  const codeVerifier = generateCodeVerifier();
  const codeChallenge = await generateCodeChallenge(codeVerifier);
  window.sessionStorage.setItem(GOOGLE_PKCE_STORAGE_KEY, codeVerifier);
  const params = new URLSearchParams({
    provider: 'google',
    redirect_to: `${origin}/`,
    code_challenge: codeChallenge,
    code_challenge_method: 'S256',
  });
  return `${supabaseUrl}/auth/v1/authorize?${params.toString()}`;
}

// Called once App.js finds a `code` query param in the post-redirect URL.
// The matching code_verifier never left this device, so only this endpoint
// (holding both halves of the pair) can complete the exchange - the server
// then verifies the resulting session against Supabase itself (never trusts
// a client-claimed email) before linking this device to whatever
// subscription is on file for the verified Google account's email.
export async function completeGoogleSignIn(code) {
  const codeVerifier = window.sessionStorage.getItem(GOOGLE_PKCE_STORAGE_KEY);
  window.sessionStorage.removeItem(GOOGLE_PKCE_STORAGE_KEY);
  if (!codeVerifier) {
    throw new Error('Could not sign in with Google.');
  }

  const deviceId = await getDeviceId();

  const response = await fetch(`${API_BASE}/api/auth`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'google', code, codeVerifier, deviceId }),
  });

  const data = await response.json();
  if (!response.ok) {
    throw serverError(data, 'authError.googleFailed');
  }

  return data.status;
}

// Cancels any live Stripe subscription and deletes all server-side data tied
// to this device (see api/auth.js's handleDelete). Does NOT clear local
// storage itself - callers must also clear the collection/profile
// photo/device id on success (see ProfileScreen.js's handleDeleteAccount).
// Unlinks THIS device from the account. The account, its password and its
// billing all stay - signing in again restores access.
//
// Not the same as deleteAccount(), which erases everything for every device.
// Before this existed the app offered a way IN with no way out: a phone that
// was sold, lent or signed into by mistake kept the previous person's
// subscription with nothing anyone could do about it.
export async function signOut() {
  const deviceId = await getDeviceId();

  const response = await fetch(`${API_BASE}/api/auth`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'signout', deviceId }),
  });

  const data = await response.json().catch(() => null);
  if (!response.ok) {
    throw serverError(data, 'restore.genericError');
  }
  return true;
}

export async function deleteAccount() {
  const deviceId = await getDeviceId();

  const response = await fetch(`${API_BASE}/api/auth`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action: 'delete', deviceId }),
  });

  const data = await response.json();
  if (!response.ok) {
    throw serverError(data, 'restore.genericError');
  }
  // true when a Hotmart subscription is still live. The caller MUST surface
  // this: unlike the old Stripe flow, deleting the account here does NOT stop
  // the recurring charge - only Hotmart can.
  return { billingStillActive: Boolean(data?.billingStillActive) };
}
